Feature setup
Bruh3509/car-ordering pull request #1
Opened 2024-08-05 16:17 UTC by Bruh3509

Создал проект, поднял в docker-compose mysql и flyway, создал таблицу users.

2024-08-05 17:20 UTC, Mishgan55 requested changes

2024-08-05 17:20 UTC, Mishgan55 commented on flyway/sql/V1__create_table_users.sql
> +CREATE TABLE users (
давай для табличек использовать имена в единственном числе, так как users зарезервированно, можешь использовать _user
для поля id вобще лучше использовать, что-то больше чем int значение.

2024-08-06 11:01 UTC, Bruh3509 commented on flyway/sql/V1__create_table_users.sql
> +CREATE TABLE users (
поправил

2024-08-06 11:16 UTC, Mishgan55 approved these changes

2024-08-06 11:16 UTC, merged