Feature user crud
Bruh3509/car-ordering pull request #2
Opened 2024-08-08 16:28 UTC by Bruh3509

Дописал CRUD, добавил testcontainers и написал немного тестов к service (потом еще допишу).

2024-08-09 09:26 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/service/impl/UserServiceImpl.java
> +    private void checkUniqueness(UserDto userDto) throws UniqueRecordException {
Here i suggest you to use Strategy pattern or switch. And create utility class for static String

2024-08-09 09:31 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/service/impl/UserServiceImpl.java
> +        var user = userRepository.findById(id).orElseThrow(UserNotFoundException::new); // а нужно ли исключение?
You can create two methods: Optional<User>findSafe(Long id) and User getById(Long id){
//Pls after second dot push enter and use convention like here:
userRepository.findById(id)
.orElseThrow(UserNotFoundException::new);
}

2024-08-09 09:43 UTC, Mishgan55 requested changes

2024-08-09 09:43 UTC, Mishgan55 commented on src/test/java/com/demo/cars/database/DbTest.java
> +@Transactional
Тесты переписать использовать Mockito

2024-08-09 09:43 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/service/impl/UserServiceImpl.java
> +            return new UserDto(); // если не найден user,
Definitely throw exception. You can find solution below

2024-08-09 09:43 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/service/UserService.java
> +    // договорились возвращать dto, но есть ли смысл тут, если и так передаем что возвращаем
UserDto saveUser(Long id, UserRequset userRequest)

2024-08-09 09:43 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/service/UserService.java
> +    UserDto updateUser(Long id, UserDto userDto) throws UserNotFoundException, UniqueRecordException;
UserDto updateUser(Long id, UserRequest userRequest) and don't use throw here

2024-08-09 09:43 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/fields/user/UserColumn.java
> +
For what?

2024-08-09 09:43 UTC, Mishgan55 commented on src/main/java/com/demo/cars/database/exception/UniqueRecordException.java
> +public class UniqueRecordException extends Exception {
ou should create Utill package and there create PropertyUtill for static fields

2024-08-09 13:43 UTC, Bruh3509 commented on src/test/java/com/demo/cars/database/DbTest.java
> +@Transactional
Окей, мне правда не совсем понятно, что тут мокать конкретно и для чего, если у меня база и все остальное крутиться в testcontainers?

2024-08-09 13:44 UTC, Bruh3509 commented on src/main/java/com/demo/cars/database/service/UserService.java
> +    // договорились возвращать dto, но есть ли смысл тут, если и так передаем что возвращаем
UserRequest это от контроллера приходить должно?

2024-08-09 13:45 UTC, Bruh3509 commented on src/main/java/com/demo/cars/database/service/UserService.java
> +    UserDto updateUser(Long id, UserDto userDto) throws UserNotFoundException, UniqueRecordException;
How can I manage unique record and user not found issues then? (if I am not throwing exceptions?)

2024-08-09 13:46 UTC, Bruh3509 commented on src/main/java/com/demo/cars/database/fields/user/UserColumn.java
> +
forgot to delete

2024-08-09 13:48 UTC, Bruh3509 commented on src/main/java/com/demo/cars/database/exception/UniqueRecordException.java
> +public class UniqueRecordException extends Exception {
Ok. I just thought that message Strings to Exception should/can be in the Exception Class

2024-08-09 13:49 UTC, Bruh3509 commented on src/main/java/com/demo/cars/database/service/impl/UserServiceImpl.java
> +    private void checkUniqueness(UserDto userDto) throws UniqueRecordException {
I was thinking about switch but didn't find out how can I use it here. I will try the Strategy pattern then

2024-08-12 18:36 UTC, Mishgan55 commented on src/main/java/com/demo/cars/CarsApplication.java
> +import org.springframework.transaction.annotation.EnableTransactionManagement;
I think you forgot to remove some imports, i suggest you to install plugin Sonarlint

2024-08-12 18:37 UTC, Mishgan55 commented on src/main/java/com/demo/cars/service/UserService.java
> +public interface UserService {
remove this comments

2024-08-12 18:37 UTC, Mishgan55 commented on src/main/java/com/demo/cars/service/impl/UserServiceImpl.java
> +import static com.demo.cars.utility.PropertyUtil.*;
Don't use wildcards for imports

2024-08-12 18:38 UTC, Mishgan55 commented on src/main/java/com/demo/cars/entity/User.java
> +import jakarta.persistence.*;
Don't use wildcards for imports

2024-08-12 18:38 UTC, Mishgan55 commented on src/main/java/com/demo/cars/service/impl/UserServiceImpl.java
> +        // validation
delete comment

2024-08-12 18:38 UTC, Bruh3509 commented on src/main/java/com/demo/cars/service/impl/UserServiceImpl.java
> +import static com.demo.cars.utility.PropertyUtil.*;
It's auto refactoring from ide I guess

2024-08-12 18:46 UTC, Mishgan55 commented on src/test/java/com/demo/cars/database/UserServiceTest.java
> +        // arrange
Please use when method, here is example:
        User user = createUser();
        UserDto userDto = createUserDto();

        // act
        when(userRepository.findAll()).thenReturn(List.of(user));
        when(userMapper.entityToDtoList(List.of(user))).thenReturn(List.of(userDto));
        var result = userService.getAllUsers();

        // assert
        assertEquals(1, result.size());
        assertEquals("JASO1921AS", result.getFirst().getPassportId());

2024-08-12 18:48 UTC, Mishgan55 commented on src/main/java/com/demo/cars/service/impl/UserServiceImpl.java
> +        // validation
delete comment

2024-08-12 18:49 UTC, Mishgan55 commented on src/main/java/com/demo/cars/utility/PropertyUtil.java
> +    public static String EMAIL_EXC = "email unique exception";
better write full name UNIQUE_EXCEPTION

2024-08-13 08:56 UTC, merged